project:
  type: book
  output-dir: docs

book:
  title: "Data Science Applications in Political Science"
  author: "Babak RezaeeDaryakenari"
  date: "5-Nov-2025"
  chapters:
    - index.qmd
    - intro.qmd
    - knn.qmd
    - NaiveBayes.qmd
    - LLM.qmd
    - TreeModels.qmd
    - NetworkAnalysis.qmd
    - ClassificationMetrics.qmd
    - Rmarkdown.qmd
    - HW1.qmd
    - HW2.qmd
    - references.qmd
  page-navigation: true  # Enables Next/Previous navigation

format:
  html:
    theme: cosmo
    number-sections: true
    toc: true  # Enables Table of Contents
    toc-depth: 2
  pdf:
    documentclass: scrreprt

bibliography: references.bib

editor: visual
